### ISSUE TITLE
import private key error in windows 10 version 1.2.1

### ISSUE THREAD

**Issue by ghost** [webchain-network/webchain-wallet#111]
![Capture](https://user-images.githubusercontent.com/49132895/58214866-f0e23b00-7d29-11e9-8a25-0f41a2ddb9e1.PNG)

**Comment by danielwebimp** [comment]
This error occurs during the import of the private key without `0x` . So for it to succeed, you must always add `0x` before the other list of characters when you want to add an address. In other words, verify your private key before importing it.
