### ISSUE TITLE
An unexpected error has occurred. Please restart & update Webchain wallet.  The error was: Invalid data format: Invalid passphrase

### ISSUE THREAD

**Issue by MATEUSCARDOSOARAO** [webchain-network/webchain-wallet#145]
``` 
JsonRpcError: Invalid data format: Invalid passphrase
    at JsonRpcError.ExtendableBuiltin (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25590:30)
    at new JsonRpcError (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25619:116)
    at file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25656:19
 ```

**Comment by danielwebimp** [comment]
> ```
> JsonRpcError: Invalid data format: Invalid passphrase
>     at JsonRpcError.ExtendableBuiltin (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25590:30)
>     at new JsonRpcError (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25619:116)
>     at file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25656:19
> ```

Hi, please check your password and make sure it's correct to proceed with the transaction.

**Comment by wivelt** [comment]
Good time of day!
I have problems logging in after resetting one pc to windows 10. After installing and downloading the key, I get an error response:

`ERROR: An unexpected error has occurred. Please restart & update emerald wallet.

The error was: Could not call remote method 'importAccount'. Check that the method signature is correct. Underlying error: internal error in Neon module: Unable to setup storage: StorageError("Can\'t create database Keyfile storage. KeyFile storage error: Keyfile storage error: IO error: No such file or directoryFailed to create a directory: C:\\Users\\Олег\\AppData\\Roaming\\.emerald\\eth\\keystore\\.db: ������� �� ������� ����� ��������� ����.\r\n") Underlying stack: Error: internal error in Neon module: Unable to setup storage: StorageError("Can\'t create database Keyfile storage. KeyFile storage error: Keyfile storage error: IO error: No such file or directoryFailed to create a directory: C:\\Users\\Олег\\AppData\\Roaming\\.emerald\\eth\\keystore\\.db: ������� �� ������� ����� ��������� ����.\r\n") at EmeraldVaultNative.importAccount (C:\Program Files\EmeraldWallet\resources\app.asar\node_modules\@emeraldpay\emerald-vault-node\lib\EmeraldVaultNative.js:17:22) at NativeVaultProvider.importAccount (C:\Program Files\EmeraldWallet\resources\app.asar\node_modules\@emeraldwallet\vault\lib\NativeProvider.js:23:29) at Vault.importAccount (C:\Program Files\EmeraldWallet\resources\app.asar\node_modules\@emeraldwallet\vault\lib\vault.js:37:30) at electron/js2c/browser_init.js:6545:63 at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6398:21) at EventEmitter.emit (events.js:203:13) at WebContents.<anonymous> (electron/js2c/browser_init.js:3788:23) at WebContents.emit (events.js:203:13)`

On the second PC, access is quietly getting access. Already checked everything that came to mind. But I can not find what the program is missing. Even forcibly asked her access to the network. Judging by the fact that I understand she does not see the Internet connection. Perhaps there is not enough extension or additional software? Is that what it has? Who knows?
