### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by khawar-nehal** [webchain-network/webchain-wallet#148]
``` 
TypeError: Failed to fetch
 ```

when creating a new account.

**Comment by danielwebimp** [comment]
Hi, you must allow the wallet to connect to Webchain Network (Number of blocks is above 2.7 Million of Blocks : http://joxi.ru/n2YqYe3IbWM972 ). The easiest way is to use remote node 1 or 2 when you open the wallet. Also make sure to open the port in your firewall to authorize your wallet to connect to Webchain Network. Wait around 30 to 60 seconds before creating wallet address.

**Comment by danielwebimp** [comment]
I think this issue can be closed
