### ISSUE TITLE
Mnemonic error: Mnemonic generation error: invalid initial sentence length

### ISSUE THREAD

**Issue by shahinalzahrani** [webchain-network/webchain-wallet#154]
``` 
JsonRpcError: Mnemonic error: Mnemonic generation error: invalid initial sentence length
    at JsonRpcError.ExtendableBuiltin (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25590:30)
    at new JsonRpcError (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25619:116)
    at file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25656:19
 ```

**Comment by shahinalzahrani** [comment]
> ```
> JsonRpcError: Mnemonic error: Mnemonic generation error: invalid initial sentence length
>     at JsonRpcError.ExtendableBuiltin (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25590:30)
>     at new JsonRpcError (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25619:116)
>     at file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25656:19
> ```

**Comment by tendo-abc** [comment]
Issue not clear  (how to reproduce it)
