### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by charchit95** [webchain-network/webchain-wallet#170]
``` 
TypeError: Failed to fetch
 ```
![image](https://user-images.githubusercontent.com/47504288/68594900-6dabd180-0490-11ea-849f-04ecc2937d12.png)

I am not able to create a new account.
Please Help..

**Comment by danielwebimp** [comment]
Before trying to create a new wallet, you must select remote node 1 or 2 and wait that the wallet should be connected to the network. You should see at least 3 millions of blocks, then you can proceed with the creation of your wallet. You can check it at the top right of the wallet.
