### ISSUE TITLE
My wallet is stuck.

### ISSUE THREAD

**Issue by eksprestren** [webchain-network/webchain-wallet#2]
My wallet was working perfect yesterday but it's stuck today.
![ekran alintisi](https://user-images.githubusercontent.com/37961775/41202915-e3c931ba-6cd8-11e8-9da4-769f07840935.PNG)
And it's not changing even after an hour.

**Comment by RonaldEAM** [comment]
@eksprestren default remote node (node1) is down temporarily, we are working to fix it, meanwhile you can delete wallet settings as it says here https://github.com/webchain-network/webchain-wallet#troubleshooting and start wallet again and choose to use full node, later when it starts you can change to node2 if you want

**Comment by eksprestren** [comment]
Thanks, I fully uninstalled it by uninstalling and deleting remaining files, so that solution worked!
