### ISSUE TITLE
Invalid address length, expected 40 got 42 bytes

### ISSUE THREAD

**Issue by alinaderi7584** [webchain-network/webchain-wallet#36]
``` 
JsonRpcError: Invalid address length, expected 40 got 42 bytes
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/nader/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:24027:30)
    at new JsonRpcError (file:///C:/Users/nader/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:24056:116)
    at file:///C:/Users/nader/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:24093:19
    at <anonymous>
 ```

**Comment by danielwebimp** [comment]
> ```
> JsonRpcError: Invalid address length, expected 40 got 42 bytes
>     at JsonRpcError.ExtendableBuiltin (file:///C:/Users/nader/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:24027:30)
>     at new JsonRpcError (file:///C:/Users/nader/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:24056:116)
>     at file:///C:/Users/nader/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:24093:19
>     at <anonymous>
> ```

Hi, now there is verification while adding accounts so this error is fixed in the new wallet in most places. But while sending coins, make sure to verify your destination address. We will probably fix that field in future release.
