### ISSUE TITLE
Unable to "open" new wallet using main nodes on Debian 9 x64

### ISSUE THREAD

**Issue by leshacat** [webchain-network/webchain-wallet#56]
Can't open wallet on local computer or remote server...

Debian 9 x64

Logs:

> root@mn1:~/WebchainWallet-linux-x64# ./webchainwallet 
> [22:30:31.868] [info] userData:  /root/.config/WebchainWallet
> [22:30:31.890] [info] Chain: {"name":null,"id":null}
> [22:30:31.891] [info] Settings:  { version: 1,
>   geth: { type: 'none', url: '' },
>   chain: { name: null, id: null },
>   terms: 'none' }
> [22:30:35.009] [info] Starting Webchain...
> [22:30:37.762] [info] Run services from /root/WebchainWallet-linux-x64/resources
> [22:30:37.815] [error] Failed to start Services: Wrong chain {"name":null,"id":null}
> [22:30:44.913] [info] index - Starting Webchain Wallet...
> [22:31:00.213] [info] launcherActions - Save settings { chain: { id: 101, name: 'mainnet' },
>   geth: 
>    { status: 'wrong settings',
>      type: 'local',
>      url: 'http://127.0.0.1:39573' } }
> [22:31:00.347] [info] Update settings { chain: { id: 101, name: 'mainnet' },
>   geth: 
>    { status: 'wrong settings',
>      type: 'local',
>      url: 'http://127.0.0.1:39573' } }
> [22:31:00.583] [info] Starting Webchain Connector...
> [22:31:01.696] [error] FetchError: request to http://localhost:39573 failed, reason: connect ECONNREFUSED 127.0.0.1:39573
>     at ClientRequest.<anonymous> (/root/WebchainWallet-linux-x64/resources/app.asar/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:133:11)
>     at emitOne (events.js:115:13)
>     at ClientRequest.emit (events.js:210:7)
>     at Socket.socketErrorListener (_http_client.js:401:9)
>     at emitOne (events.js:115:13)
>     at Socket.emit (events.js:210:7)
>     at emitErrorNT (internal/streams/destroy.js:64:8)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
> 
> [22:31:01.708] [info] Can't find existing RPC. Try to launch
> [22:31:03.966] [info] Downloading webchaind from https://github.com/webchain-network/webchaind/releases/download/v0.2.0/webchaind-0.2.0-linux-amd64.zip to /tmp/download-webchaind-dStuKS/
> [22:31:04.212] [error] Webchain Connector process exited with code: 127
> [22:31:05.848] [info] Downloaded /tmp/download-webchaind-dStuKS/dist.zip
> [22:31:05.854] [info] Downloading PGP keys from https://github.com/webchain-network/webchaind/releases/download/v0.2.0/webchaind-0.2.0-linux-amd64.zip.asc
> [22:31:06.059] [info] Verifying PGP signature
> [22:31:08.801] [info] Unpacking /tmp/download-webchaind-dStuKS/dist.zip to /root/WebchainWallet-linux-x64/resources/webchaind
> [22:31:11.647] [info] Cleaning up. Removing /tmp/download-webchaind-dStuKS/dist.zip
> [22:31:11.831] [info] Starting Webchaind... [bin: /root/WebchainWallet-linux-x64/resources network: mainnet, port: 39573]
> [22:31:15.468] [info] RPC is ready: webchaind/v0.2.0/linux/go1.10rc2
> [22:31:22.401] [info] launcherActions - Save settings { chain: 
>    { client: 'webchaind/v0.2.0/linux/go1.10rc2',
>      id: 101,
>      name: 'mainnet' },
>   geth: { status: 'ready', type: 'local', url: 'http://127.0.0.1:39573' } }
> [22:31:22.524] [info] Update settings { chain: 
>    { client: 'webchaind/v0.2.0/linux/go1.10rc2',
>      id: 101,
>      name: 'mainnet' },
>   geth: { status: 'ready', type: 'local', url: 'http://127.0.0.1:39573' } }
> [22:31:22.624] [info] Shutting down Local Webchaind
> [22:31:22.739] [info] Shutting down Local Connector
> [22:31:23.758] [error] webchaind process exited with code: 0
> [22:31:23.875] [info] Starting Webchain Connector...
> [22:31:24.352] [error] FetchError: request to http://localhost:39573 failed, reason: connect ECONNREFUSED 127.0.0.1:39573
>     at ClientRequest.<anonymous> (/root/WebchainWallet-linux-x64/resources/app.asar/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:133:11)
>     at emitOne (events.js:115:13)
>     at ClientRequest.emit (events.js:210:7)
>     at Socket.socketErrorListener (_http_client.js:401:9)
>     at emitOne (events.js:115:13)
>     at Socket.emit (events.js:210:7)
>     at emitErrorNT (internal/streams/destroy.js:64:8)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
> 
> [22:31:24.355] [info] Can't find existing RPC. Try to launch
> [22:31:24.446] [info] Starting Webchaind... [bin: /root/WebchainWallet-linux-x64/resources network: mainnet, port: 39573]
> [22:31:24.644] [error] Webchain Connector process exited with code: 127
> [22:31:27.744] [info] RPC is ready: webchaind/v0.2.0/linux/go1.10rc2
> [22:31:40.122] [info] Shutting down Local Webchaind
> [22:31:40.144] [info] Shutting down Local Connector
> [22:31:40.343] [error] webchaind process exited with code: 0
> [22:31:40.351] [info] All services are stopped
> root@mn1:~/WebchainWallet-linux-x64#

also tried with Wine but says it requires windows 7.

What else to do? tks

**Comment by leshacat** [comment]
I opened a wallet inside a Win7 VM and can send and receive WEB temporarily, but it would be nice to get the Linux version working.

**Comment by tendo-abc** [comment]
Hello,  our latest version should be working perfectly https://github.com/webchain-network/webchain-wallet/releases
