### ISSUE TITLE
반입 하지 못했습니다.

### ISSUE THREAD

**Issue by hyuninbong** [webchain-network/webchain-wallet#66]
``` 
TypeError: Failed to fetch 
 While processing action: 
 function (dispatch, getState, api) {
    return api.geth.eth.getSyncing().then(function (result) {
      if ((typeof result === 'undefined' ? 'undefined' : _typeof(result)) === 'object') {
        return dispatch({
          type: _actionTypes2.default.SYNCING,
          syncing: true,
          status: result
        });
      }

      dispatch({
        type: _actionTypes2.default.SYNCING,
        syncing: false
      });
    });
  }
 ```

**Comment by danielwebimp** [comment]
> ```
> TypeError: Failed to fetch 
>  While processing action: 
>  function (dispatch, getState, api) {
>     return api.geth.eth.getSyncing().then(function (result) {
>       if ((typeof result === 'undefined' ? 'undefined' : _typeof(result)) === 'object') {
>         return dispatch({
>           type: _actionTypes2.default.SYNCING,
>           syncing: true,
>           status: result
>         });
>       }
> 
>       dispatch({
>         type: _actionTypes2.default.SYNCING,
>         syncing: false
>       });
>     });
>   }
> ```

Hi, you must allow the wallet to connect to Webchain Network (Number of blocks is above 2.5 Million of Blocks). The easiest way is to use remote node 1 or 2 when you open the wallet. Also make sure to open the port in your firewall to authorize your wallet to connect to Webchain Network.

**Comment by danielwebimp** [comment]
It's a common issue that users have and it's solve that way. So I think it can be closed.
