### ISSUE TITLE
The error was: Invalid data format: Invalid passphrase

### ISSUE THREAD

**Issue by isaack0815** [webchain-network/webchain-wallet#67]
I use the wallet for Ubuntu and get the following message when I want to send WEB:
ERROR: An unexpected error has occured. Please restart & update Webchain wallet.
The error was: Invalid data format: Invalid passphrase
I have already restarted and unfortunately there is currently no release.

in the log the following lines are available:

> [2019-03-23 07:30:57.228] [error] screenActions - Show error JsonRpcError: Invalid data format: Invalid passphrase
    at JsonRpcError.ExtendableBuiltin (file:///opt/WebchainWallet/resources/app.asar/app/index.js:23896:30)
    at new JsonRpcError (file:///opt/WebchainWallet/resources/app.asar/app/index.js:23925:116)
    at file:///opt/WebchainWallet/resources/app.asar/app/index.js:23962:19
    at <anonymous>

**Comment by danielwebimp** [comment]
> I use the wallet for Ubuntu and get the following message when I want to send WEB:
> ERROR: An unexpected error has occured. Please restart & update Webchain wallet.
> The error was: Invalid data format: Invalid passphrase
> I have already restarted and unfortunately there is currently no release.
> 
> in the log the following lines are available:
> 
> > [2019-03-23 07:30:57.228] [error] screenActions - Show error JsonRpcError: Invalid data format: Invalid passphrase
> > at JsonRpcError.ExtendableBuiltin (file:///opt/WebchainWallet/resources/app.asar/app/index.js:23896:30)
> > at new JsonRpcError (file:///opt/WebchainWallet/resources/app.asar/app/index.js:23925:116)
> > at file:///opt/WebchainWallet/resources/app.asar/app/index.js:23962:19
> > at

Hi, please check again your password and make sure it's correct. This error happens if you entered a wrong password to proceed with the transaction.
