### ISSUE TITLE
Account does not exist or account balance too low

### ISSUE THREAD

**Issue by waseeld** [webchain-network/webchain-wallet#88]
``` 
JsonRpcError: Account does not exist or account balance too low
    at JsonRpcError.ExtendableBuiltin (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25480:30)
    at new JsonRpcError (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25509:116)
    at file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25546:19
 ```

**Comment by danielwebimp** [comment]
> ```
> JsonRpcError: Account does not exist or account balance too low
>     at JsonRpcError.ExtendableBuiltin (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25480:30)
>     at new JsonRpcError (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25509:116)
>     at file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25546:19
> ```

Try to send a number of coins which is smaller than your balance
